### ISSUE TITLE
Spaming console on startup. Maybe conflict with the new version of PlaceholderAPI

### ISSUE THREAD

**Issue by sea019vn** [TrMenu/TrMenu#128]
Log here: 

`[11:08:22 WARN]: [TrMenu] Plugin TrMenu v1.22 generated an exception while executing task 23
java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPIPlugin.getExpansionCloud()Lme/clip/placeholderapi/expansion/cloud/ExpansionCloudManager;
        at me.arasple.mc.trmenu.menu.Menu.checkDepends(Menu.java:415) ~[?:?]
        at me.arasple.mc.trmenu.menu.Menu.setValues(Menu.java:97) ~[?:?]
        at me.arasple.mc.trmenu.menu.Menu.<init>(Menu.java:68) ~[?:?]
        at me.arasple.mc.trmenu.menu.MenuLoader.loadMenu(MenuLoader.java:232) ~[?:?]
        at me.arasple.mc.trmenu.menu.MenuLoader.lambda$null$0(MenuLoader.java:63) ~[?:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:?]
        at me.arasple.mc.trmenu.menu.MenuLoader.lambda$null$1(MenuLoader.java:63) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
        at me.arasple.mc.trmenu.menu.MenuLoader.lambda$loadMenus$4(MenuLoader.java:61) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[paper.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[paper.jar:git-Paper-33d42c8e]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper.jar:git-Paper-33d42c8e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Arasple** [comment]
Please update to TrMenu v2
