### ISSUE TITLE
Warnings and commands on menus not works

### ISSUE THREAD

**Issue by Yan-Mihaylov** [TrMenu/TrMenu#144]
When I changed the version TrMenu-1.22 to TrMenu-2.03-DEV I got several warnings. Result of that warning the commands from the menus stopped working but all the menus were loaded. I contact the support discord and they tell me to delete the Taboolib folder from the plugins folder and the lib folder from the server folder. After that the warnings were double from the first time and no command from the menus was working again.

WARNINGS BEFORE DELETING THE FOLDERS:

[12:52:32 WARN]: java.lang.NoClassDefFoundError: Lio/izzel/taboolib/module/config/TConfig;
[12:52:32 WARN]:        at java.lang.Class.getDeclaredFields0(Native Method)
[12:52:32 WARN]:        at java.lang.Class.privateGetDeclaredFields(Unknown Source)
[12:52:32 WARN]:        at java.lang.Class.getDeclaredField(Unknown Source)
[12:52:32 WARN]:        at me.arasple.mc.trmenu.boot.PluginBase.<clinit>(PluginBase.java:234)
[12:52:32 WARN]:        at java.lang.Class.forName0(Native Method)
[12:52:32 WARN]:        at java.lang.Class.forName(Unknown Source)
[12:52:32 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68)
[12:52:32 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137)
[12:52:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397)
[12:52:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305)
[12:52:32 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:388)
[12:52:32 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208)
[12:52:32 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941)
[12:52:32 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[12:52:32 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:52:32 WARN]: Caused by: java.lang.ClassNotFoundException: io.izzel.taboolib.module.config.TConfig
[12:52:32 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[12:52:32 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171)
[12:52:32 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[12:52:32 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:52:32 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:52:32 WARN]:        ... 15 more

WARNING AFTER THE DELETING OF THE FOLDERS

[13:06:11] [Server thread/WARN]: java.lang.NoClassDefFoundError: Lio/izzel/taboolib/module/config/TConfig;
[13:06:11] [Server thread/WARN]: 	at java.lang.Class.getDeclaredFields0(Native Method)
[13:06:11] [Server thread/WARN]: 	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
[13:06:11] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Unknown Source)
[13:06:11] [Server thread/WARN]: 	at me.arasple.mc.trmenu.boot.PluginBase.<clinit>(PluginBase.java:234)
[13:06:11] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[13:06:11] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[13:06:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68)
[13:06:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137)
[13:06:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397)
[13:06:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305)
[13:06:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:388)
[13:06:11] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208)
[13:06:11] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941)
[13:06:11] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[13:06:11] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:06:11] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: io.izzel.taboolib.module.config.TConfig
[13:06:11] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[13:06:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171)
[13:06:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[13:06:11] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:06:11] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:06:11] [Server thread/WARN]: 	... 15 more

[13:07:30] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[13:07:30] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:07:30] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.module.inject.TScheduleLoader$2.run(TScheduleLoader.java:65)
[13:07:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[13:07:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[13:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:950)
[13:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[13:07:30] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:07:30] [Server thread/WARN]: Caused by: java.lang.TypeNotPresentException: Type me/arasple/mc/trmenu/display/Menu not present
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1025)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.SymbolTable.addMergedType(SymbolTable.java:1200)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.Frame.merge(Frame.java:1299)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.Frame.merge(Frame.java:1244)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.MethodVisitor.visitMaxs(MethodVisitor.java:771)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.ClassReader.readCode(ClassReader.java:2640)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.ClassReader.readMethod(ClassReader.java:1492)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.ClassReader.accept(ClassReader.java:717)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.ClassReader.accept(ClassReader.java:401)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.module.lite.SimpleVersionControl.translate(SimpleVersionControl.java:149)
[13:07:30] [Server thread/WARN]: 	at me.arasple.mc.trmenu.modules.packets.PacketsHandler$Companion.init(PacketsHandler.kt:55)
[13:07:30] [Server thread/WARN]: 	... 10 more
[13:07:30] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: me.arasple.mc.trmenu.display.Menu
[13:07:30] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[13:07:30] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1023)
[13:07:30] [Server thread/WARN]: 	... 22 more
[13:07:30] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[13:07:30] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:07:30] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.module.inject.TScheduleLoader$2.run(TScheduleLoader.java:68)
[13:07:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[13:07:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[13:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:950)
[13:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[13:07:30] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:07:30] [Server thread/WARN]: Caused by: java.lang.TypeNotPresentException: Type me/arasple/mc/trmenu/display/Menu not present
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1025)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.SymbolTable.addMergedType(SymbolTable.java:1200)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.Frame.merge(Frame.java:1299)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.Frame.merge(Frame.java:1244)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.MethodVisitor.visitMaxs(MethodVisitor.java:771)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.ClassReader.readCode(ClassReader.java:2640)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.ClassReader.readMethod(ClassReader.java:1492)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.ClassReader.accept(ClassReader.java:717)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.ClassReader.accept(ClassReader.java:401)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.module.lite.SimpleVersionControl.translate(SimpleVersionControl.java:149)
[13:07:30] [Server thread/WARN]: 	at me.arasple.mc.trmenu.modules.packets.PacketsHandler$Companion.init(PacketsHandler.kt:55)
[13:07:30] [Server thread/WARN]: 	... 10 more
[13:07:30] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: me.arasple.mc.trmenu.display.Menu
[13:07:30] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[13:07:30] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[13:07:30] [Server thread/WARN]: 	at io.izzel.taboolib.internal.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1023)
[13:07:30] [Server thread/WARN]: 	... 22 more

**Comment by Galaxy-VN** [comment]
Did you migrate a menu v1 to v2 yet ?

**Comment by Sikatsu** [comment]
Have these as well https://pastebin.com/m5Q7R7yf

**Comment by Arasple** [comment]
Fixed. Download the latest build
