### ISSUE TITLE
Spigot 1.16.2 compatibility

### ISSUE THREAD

**Issue by sea019vn** [TrMenu/TrMenu#152]
**Describe the bug**

**Plugins**
 - TrMenu 2.03-DEV
 - PlaceholderAPI 2.10.9

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - OS: [e.g. Windows Server 2019]
 - JDK: [e.g.1.8.0_261]

**Additional context**
`[10:44:22] [Server thread/INFO]: [TrMenu] Enabling TrMenu v2.03
[10:44:22] [Server thread/INFO]: [TabooLib][ERROR] init is not a static method. (me.arasple.mc.trmenu.modules.service.update.Updater)
[10:44:22] [Server thread/WARN]: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Class java.lang.ClassLoader.findClass(java.lang.String) throws java.lang.ClassNotFoundException accessible: module java.base does not "opens java.lang" to unnamed module @694d33bc
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.util.Reflection.getMethod(Reflection.java:123)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.common.plugin.bridge.BridgeLoader.<init>(BridgeLoader.java:20)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.common.plugin.bridge.BridgeLoader.createNewClass(BridgeLoader.java:40)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.module.lite.SimpleVersionControl.translate(SimpleVersionControl.java:155)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.module.inject.TInjectAsm.postLoad(TInjectAsm.java:25)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.TabooLibLoader.lambda$postLoadClass$4(TabooLibLoader.java:145)
[10:44:22] [Server thread/WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.TabooLibLoader.postLoadClass(TabooLibLoader.java:142)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.PluginLoader$1.onStarting(PluginLoader.java:64)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.PluginLoader.lambda$start$2(PluginLoader.java:143)
[10:44:22] [Server thread/WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.PluginLoader.start(PluginLoader.java:143)
[10:44:22] [Server thread/WARN]:        at me.arasple.mc.trmenu.boot.PluginBase.onEnable(PluginBase.java:60)
[10:44:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:44:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[10:44:22] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[10:44:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492)
[10:44:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[10:44:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435)
[10:44:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:219)
[10:44:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808)
[10:44:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[10:44:22] [Server thread/WARN]: java.lang.NoClassDefFoundError: me/arasple/mc/trmenu/api/nms/NMS
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.common.plugin.bridge.BridgeLoader.createNewClass(BridgeLoader.java:40)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.module.lite.SimpleVersionControl.translate(SimpleVersionControl.java:155)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.module.inject.TInjectAsm.postLoad(TInjectAsm.java:25)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.TabooLibLoader.lambda$postLoadClass$4(TabooLibLoader.java:145)
[10:44:22] [Server thread/WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.TabooLibLoader.postLoadClass(TabooLibLoader.java:142)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.PluginLoader$1.onStarting(PluginLoader.java:64)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.PluginLoader.lambda$start$2(PluginLoader.java:143)
[10:44:22] [Server thread/WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.PluginLoader.start(PluginLoader.java:143)
[10:44:22] [Server thread/WARN]:        at me.arasple.mc.trmenu.boot.PluginBase.onEnable(PluginBase.java:60)
[10:44:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:44:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[10:44:22] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[10:44:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492)
[10:44:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[10:44:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435)
[10:44:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:219)
[10:44:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808)
[10:44:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[10:44:22] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: me.arasple.mc.trmenu.api.nms.NMS
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:718)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.common.plugin.bridge.BridgeLoader.findClass(BridgeLoader.java:36)
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[10:44:22] [Server thread/WARN]:        ... 23 more
[10:44:22] [Server thread/INFO]: [TabooLib][ERROR] grabInfo is not a static method. (me.arasple.mc.trmenu.modules.service.update.Updater)
[10:44:22] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[10:44:22] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:44:22] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:44:22] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.util.Reflection.invokeMethod(Reflection.java:160)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.module.inject.TInjectCreator.eval(TInjectCreator.java:75)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.module.inject.TInjectCreator.postLoad(TInjectCreator.java:37)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.TabooLibLoader.lambda$postLoadClass$4(TabooLibLoader.java:145)
[10:44:22] [Server thread/WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.TabooLibLoader.postLoadClass(TabooLibLoader.java:142)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.PluginLoader$1.onStarting(PluginLoader.java:64)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.PluginLoader.lambda$start$2(PluginLoader.java:143)
[10:44:22] [Server thread/WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[10:44:22] [Server thread/WARN]:        at io.izzel.taboolib.PluginLoader.start(PluginLoader.java:143)
[10:44:22] [Server thread/WARN]:        at me.arasple.mc.trmenu.boot.PluginBase.onEnable(PluginBase.java:60)
[10:44:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:44:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[10:44:22] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[10:44:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492)
[10:44:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[10:44:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435)
[10:44:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:219)
[10:44:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808)
[10:44:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[10:44:22] [Server thread/WARN]: Caused by: java.lang.NoClassDefFoundError: kotlin/text/StringsKt
[10:44:22] [Server thread/WARN]:        at me.arasple.mc.trmenu.TrMenuLoader.printLogo(TrMenuLoader.kt:79)
[10:44:22] [Server thread/WARN]:        at me.arasple.mc.trmenu.TrMenuLoader.init(TrMenuLoader.kt:24)
[10:44:22] [Server thread/WARN]:        ... 25 more
[10:44:22] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: kotlin.text.StringsKt
[10:44:22] [Server thread/WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[10:44:22] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167)
[10:44:22] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96)
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[10:44:22] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[10:44:22] [Server thread/WARN]:        ... 27 more
[10:44:22] [Server thread/ERROR]: Error occurred while enabling TrMenu v2.03 (Is it up to date?)
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
        at me.arasple.mc.trmenu.modules.command.sub.CommandMigrate.<init>(CommandMigrate.kt:24) ~[?:?]
        at me.arasple.mc.trmenu.modules.command.CommandHandler.<init>(CommandHandler.kt:39) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at io.izzel.taboolib.module.command.TCommandHandler.registerCommand(TCommandHandler.java:153) ~[TabooLib.jar:?]
        at io.izzel.taboolib.PluginLoader$1.onStarting(PluginLoader.java:66) ~[TabooLib.jar:?]
        at io.izzel.taboolib.PluginLoader.lambda$start$2(PluginLoader.java:143) ~[TabooLib.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
        at io.izzel.taboolib.PluginLoader.start(PluginLoader.java:143) ~[TabooLib.jar:?]
        at me.arasple.mc.trmenu.boot.PluginBase.onEnable(PluginBase.java:60) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Spigot.jar:git-Spigot-379750e-43c7ff9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[Spigot.jar:git-Spigot-379750e-43c7ff9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[Spigot.jar:git-Spigot-379750e-43c7ff9]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492) ~[Spigot.jar:git-Spigot-379750e-43c7ff9]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406) ~[Spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[Spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:219) ~[Spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[Spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[Spigot.jar:git-Spigot-379750e-43c7ff9]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[Spigot.jar:git-Spigot-379750e-43c7ff9]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[Spigot.jar:git-Spigot-379750e-43c7ff9]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 23 more`

**Comment by Arasple** [comment]
I can't reproduce this issue on the latest spigot
Please check it again to see if it is still there, if it is, provide a full server log
