### ISSUE TITLE
点击菜单任何地方都会掉线[已解决]

### ISSUE THREAD

**Issue by YsGqHY** [TrMenu/TrMenu#159]
**Describe the bug**

**Server Software**
git-Spigot-642f6d2-57ab4cf (MC: 1.12.2)

**Plugins**
 - TrMenu 2.03

**To Reproduce**
1. 打开菜单
2. 点击任何地方，包括菜单GUI外

**Expected behavior**
打开菜单后，点击任何一个地方，玩家就会掉线，按钮效果一样有效

**Screenshots**
https://s1.ax1x.com/2020/08/24/dDqUsg.png

**Environment(please complete the following information):**
 - OS: [e.g. Windows Server 2016]
 - JDK: [e.g.jdk-14.0.2.12]

**Additional context**
可能不是同一问题，但也有报错
[15:23:00 INFO]: __Curtain__ lost connection: Disconnected
[15:23:00 INFO]: __Curtain__ left the game
[15:23:02 WARN]: java.io.FileNotFoundException: https://api.ashcon.app/mojang/v2/user/__Curtain__

[15:23:02 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1928)

[15:23:02 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)

[15:23:02 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)

[15:23:02 WARN]:        at java.base/java.net.URL.openStream(URL.java:1167)

[15:23:02 WARN]:        at me.arasple.mc.trmenu.boot.internal.IO.readFromURL(IO.java:43)

[15:23:02 WARN]:        at me.arasple.mc.trmenu.util.Skulls$getPlayerTexture$1.run(Skulls.kt:77)

[15:23:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)

[15:23:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)

[15:23:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)

[15:23:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

[15:23:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by YsGqHY** [comment]
已解决，问题出自LibDisguise插件上
LibDisguise/config.yml
RemoveArmor: true 修改为false重载插件即可
