### ISSUE TITLE
menu don't work

### ISSUE THREAD

**Issue by V3ervee** [TrMenu/TrMenu#219]
menu did not open
 i want some menu like voucher with Type: ANVIL 

Tanguygab send me this code:

Title:
  - 'CODE'
Type: ANVIL

Options:
  Arguments: false
  Hide-Player-Inventory: true
  Depend-Expansions: ['server', 'player', 'progress', 'animations']

Bindings:
  Commands:
    - '(?i)code(-)?(gui)?(s)?'

Events:
  Open:
    - condition: 'hasPerm.trmenu.use or is.{reason}.RELOAD or is.{reason}.CONSOLE'
      actions:
        - 'sound: BLOCK_CHEST_OPEN-1-0'
      deny:
        - 'sound: ENTITY_ITEM_BREAK-1-0'
        - 'title: <title=&c&lPermission Required><subtitle=&7&lYou need permission &6&ltrmenu.use &7&lto open this menu>'
        - 'return'
  Close:
    - 'sound: BLOCK_CHEST_CLOSE-1-0'

Icons:
  '#':
    display:
      material: Paper
      name: '&7Paste code here!'
      slot: 0
    actions:
      all:
        - catcher:
          target:
            type: ANVIL
            before: 'tell: Enter code here'
            cancel: 'tell: Cancelled...'
            reactions:
              - condition: 'equals."${input_target}".codehere'
                execute:
                  - 'tell: You entered the right code and received 4 diamonds! ${input_target}'
                  - 'give-item: material:diamond,amount:4'
                deny:
                  - 'tell: Invalid code, no diamonds for you! ${input_target}'
                  - 'return'
but menu do not open, nothing in chat
it write in console this wrong:

[22:22:10 INFO]: V3ervee issued server command: /code
[22:22:10 WARN]: Exception in thread "Craft Scheduler Thread - 3"
[22:22:10 WARN]: org.apache.commons.lang.UnhandledException: Plugin TrMenu v2.06-DEV generated an exception while executing task 192
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at me.arasple.mc.trmenu.modules.display.Menu$open$1.run(Menu.kt:87)
        at me.arasple.mc.trmenu.modules.service.mirror.MirrorData.eval(MirrorData.kt:37)
        at me.arasple.mc.trmenu.modules.service.mirror.MirrorData$evalAsync$1.run(MirrorData.kt:44)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

I don't know what to do with it, can you help me?

TrMenu Dump Information (2020-10-05 20:05:29)

| Server software: AtomSpigot 1.8.8
| Java version: 1.8

| TabooLib: 5.37
| TrMenu: 2.06-DEV / Tue Oct 06 04:03:33 CST 2020 (Built by Arasple)

Installed Plugins: 
· ProtocolLib
· Vault-1.7.3
· PlaceholderAPI-2.10.6
· TrMenu - 2.06-DEV
```

**Comment by Arasple** [comment]
Menu must have layout or specified size
