### ISSUE TITLE
Error with skull on cracked server

### ISSUE THREAD

**Issue by BBSnowIce** [TrMenu/TrMenu#239]
**Describe the bug**
An error is thrown when the plugin tries to load the skull of a cracked player. Despite the error, the default skull is shown.
```
[13:27:01] [Craft Scheduler Thread - 1580/WARN]: java.io.FileNotFoundException: https://api.ashcon.app/mojang/v2/user/idemao
[13:27:01] [Craft Scheduler Thread - 1580/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)
[13:27:01] [Craft Scheduler Thread - 1580/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[13:27:01] [Craft Scheduler Thread - 1580/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[13:27:01] [Craft Scheduler Thread - 1580/WARN]: 	at java.net.URL.openStream(URL.java:1067)
[13:27:01] [Craft Scheduler Thread - 1580/WARN]: 	at me.arasple.mc.trmenu.boot.internal.IO.readFromURL(IO.java:41)
[13:27:01] [Craft Scheduler Thread - 1580/WARN]: 	at me.arasple.mc.trmenu.util.Skulls$getPlayerTexture$1.run(Skulls.kt:77)
[13:27:01] [Craft Scheduler Thread - 1580/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[13:27:01] [Craft Scheduler Thread - 1580/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:27:01] [Craft Scheduler Thread - 1580/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:27:01] [Craft Scheduler Thread - 1580/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:27:01] [Craft Scheduler Thread - 1580/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:27:01] [Craft Scheduler Thread - 1580/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
1. Put a <skull:%player_name%> as a material in a menu
2. Connect with a cracked player name
3. The error is thrown in console

**Expected behavior**
No error thrown in console

**Server Information**
```
TrMenu Dump Information (2020-11-18 13:39:22)

| Server OS: Linux amd64 4.19.0-9-amd64
| Server software: git-Paper-1618 (MC: 1.12.2) (1.12.2-R0.1-SNAPSHOT)
| Java version: 1.8.0_251

| TabooLib: 5.41
| TrMenu: 2.07 / Sat Nov 14 22:57:12 CET 2020 (Built by Arasple)

Installed Plugins: 
· LuckPerms - 5.1.98
· PlaceholderAPI - 2.10.9
· TrMenu - 2.07-DEV
```

**Comment by Arasple** [comment]
If you are an offline server, use `<SkinsRestorer:%player_name%>`
