### ISSUE TITLE
不斷重複地跳出錯誤代碼

### ISSUE THREAD

**Issue by itisnet2468** [TrMenu/TrMenu#252]
**Describe the bug**
我剛買插件 
放上去開Example選單後就有這些錯誤代碼一直跳 
請問是什麼問題 
另外 
我的Lib是手動下載的 他自己抓不到

**Expected behavior**
解除這個錯誤代碼

**Server Information**
TrMenu Dump Information (2020-12-06 15:44:50)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Paper-312 (MC: 1.16.4) (1.16.4-R0.1-SNAPSHOT)
| Java version: 11.0.9.1

| TabooLib: 5.44
| TrMenu: 2.08 / Sat Dec 05 00:23:29 CST 2020 (Built by Arasple)

Installed Plugins: 
· Admin-GUI - 1.4.5
· CMI - 8.7.11.2
· CMIPaperLib - 1.0.0
· Companions - 1.8.3
· EpicCraftingsPlus - 6.3.8
· HeadDatabase - 4.13.0
· LibsDisguises - 10.0.20
· LuckPerms - 5.2.35
· MMOCore - 1.5
· MMOItems - 6.4
· MMOLib - 1.6
· Multiverse-Core - 4.2.2-b812
· MythicMobs - 4.11.0-SNAPSHOT-5c665e39
· Oraxen - 1.63.2
· PlaceholderAPI - 2.10.9
· ProtocolLib - 4.6.0-SNAPSHOT-b483
· Residence - 4.9.2.1
· TheNewEconomy - 0.1.1.12
· TrMenu - 2.08
· Vault - 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
· WorldEdit - 7.2.0+a51fa43
· WorldGuard - 7.0.4+f7ff984

錯誤代碼如下：
[23:22:55 WARN]: java.lang.IllegalStateException: PlayerKeepAliveEvent may only be triggered synchronously.
[23:22:55 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595)
[23:22:55 WARN]: at io.izzel.taboolib.module.event.EventNormal.call(EventNormal.java:28)
[23:22:55 WARN]: at io.izzel.taboolib.common.listener.ListenerPlayer.e(ListenerPlayer.java:36)
[23:22:55 WARN]: at jdk.internal.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
[23:22:55 WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:22:55 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[23:22:55 WARN]: at io.izzel.taboolib.module.packet.TPacketLoader.eval(TPacketLoader.java:74)
[23:22:55 WARN]: at io.izzel.taboolib.module.packet.TPacketLoader.access$000(TPacketLoader.java:19)
[23:22:55 WARN]: at io.izzel.taboolib.module.packet.TPacketLoader$2.onReceive(TPacketLoader.java:59)
[23:22:55 WARN]: at io.izzel.taboolib.module.packet.channel.ChannelExecutor$ChannelHandler.lambda$channelRead$1(ChannelExecutor.java:68)
[23:22:55 WARN]: at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[23:22:55 WARN]: at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
[23:22:55 WARN]: at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:278)
[23:22:55 WARN]: at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1696)
[23:22:55 WARN]: at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
[23:22:55 WARN]: at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
[23:22:55 WARN]: at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
[23:22:55 WARN]: at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[23:22:55 WARN]: at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[23:22:55 WARN]: at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[23:22:55 WARN]: at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[23:22:55 WARN]: at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
[23:22:55 WARN]: at io.izzel.taboolib.module.packet.channel.ChannelExecutor$ChannelHandler.channelRead(ChannelExecutor.java:68)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:22:55 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:22:55 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[23:22:55 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:22:55 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[23:22:55 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:22:55 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:22:55 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[23:22:55 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:22:55 WARN]: at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:22:55 WARN]: at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:22:55 WARN]: at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[23:22:55 WARN]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[23:22:55 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[23:22:55 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[23:22:55 WARN]: at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[23:22:55 WARN]: at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
[23:22:55 WARN]: at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547)
[23:22:55 WARN]: at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501)
[23:22:55 WARN]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
[23:22:55 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[23:22:55 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Arasple** [comment]
Use command `libupdate` in the console
