### ISSUE TITLE
关闭服务器时报错

### ISSUE THREAD

**Issue by Super-10** [TrMenu/TrMenu#273]
**Describe the bug**
使用Stop停止服务器时出现这个错误

**To Reproduce**
1.Stop

**Expected behavior**
无异常.

**Screenshots**
![image](https://user-images.githubusercontent.com/65401527/104839934-63405f80-58ff-11eb-894b-ee9f0ca99d1d.png)

**Additional context**
[20:04:01 INFO]: [TrMenu] Disabling TrMenu v2.08
[20:04:01 WARN]: java.lang.reflect.InvocationTargetException
[20:04:01 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:04:01 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:04:01 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:04:01 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[20:04:01 WARN]:        at io.izzel.taboolib.util.Reflection.invokeMethod(Reflection.java:160)
[20:04:01 WARN]:        at io.izzel.taboolib.module.inject.TInjectCreator.eval(TInjectCreator.java:75)
[20:04:01 WARN]:        at io.izzel.taboolib.module.inject.TInjectCreator.unload(TInjectCreator.java:48)
[20:04:01 WARN]:        at io.izzel.taboolib.TabooLibLoader.lambda$unloadClass$9(TabooLibLoader.java:270)
[20:04:01 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[20:04:01 WARN]:        at io.izzel.taboolib.TabooLibLoader.unloadClass(TabooLibLoader.java:267)
[20:04:01 WARN]:        at io.izzel.taboolib.PluginLoader$1.onStopping(PluginLoader.java:99)
[20:04:01 WARN]:        at io.izzel.taboolib.PluginLoader.lambda$stop$5(PluginLoader.java:229)
[20:04:01 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[20:04:01 WARN]:        at io.izzel.taboolib.PluginLoader.stop(PluginLoader.java:229)
[20:04:01 WARN]:        at me.arasple.mc.trmenu.boot.PluginBase.onDisable(PluginBase.java:77)
[20:04:01 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[20:04:01 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
[20:04:01 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422)
[20:04:01 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415)
[20:04:01 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:349)
[20:04:01 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:465)
[20:04:01 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:613)
[20:04:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[20:04:01 WARN]: Caused by: java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPIPlugin.getLocalExpansionManager()Lme/clip/placeholderapi/expansion/manager/LocalExpansionManager;
[20:04:01 WARN]:        at me.arasple.mc.trmenu.TrMenuLoader.cancel(TrMenuLoader.kt:39)
[20:04:01 WARN]:        ... 23 more

**Server Information**
> Use command `/trmenu dump` to get the information
> Copy the information to below
null
```
TrMenu Dump Information (2020-12-4 17:25:00)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
| Java version: 1.8.0_251

| TabooLib: 5.46
| TrMenu: 2.08 /Mon Nov 30 11:39:09 UTC 2020 (Built by Arasple)

Installed Plugins: 
· EssentialsX-2.18.1.0
· FastAsyncWorldEdit-bukkit-19.11.13-5505943-1282-22.3.5
· LuckPerms-Bukkit-5.1.106
· PlugMan-2.1.7
· TrMenu - 2.08
· PlaceholderAPI-2.10.6
· ProtocolLib-4.5.0
· React-6.639
· ShopGUIPlus-1.48.0
· ViaBackwards-3.2.0
· ViaRewind-1.5.2
· ViaVersion-3.2.0
· Vault-1.7.2-b107
· worldedit-bukkit-6.1.9
· worldguard-bukkit-6.2.2
· ShopGUIPlusSilkSpawnersBridge-1.2.1
· SilkSpawners-5.0.2

**Comment by Arasple** [comment]
```
[20:04:01 WARN]: Caused by: java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPIPlugin.getLocalExpansionManager()Lme/clip/placeholderapi/expansion/manager/LocalExpansionManager;
```
PlaceholderAPI 版本过低
